### ISSUE TITLE
There seems to be some files missing (import errors)

### ISSUE THREAD

**Issue by KiyarashFarivar** [bharat-b7/IPNet#10]
Hi

I was trying your code but it seems there are functions/ files missing for the imports.

this is the error message I get when I try to run the demo:

```
(kaolin2) PS C:\Users\User\Desktop\Kiarash\IPNet> python test_IPNet.py assets/scan.obj experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar out_dir -m IPNet
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Kiarash\IPNet\utils\implicit_waterproofing.py", line 9, in <module>
    from .libs.libmesh import check_mesh_contains
  File "C:\Users\User\Desktop\Kiarash\IPNet\utils\libs\libmesh\__init__.py", line 1, in <module>
    from .inside_mesh import check_mesh_contains, MeshIntersector, TriangleIntersector2d
  File "C:\Users\User\Desktop\Kiarash\IPNet\utils\libs\libmesh\inside_mesh.py", line 3, in <module>
    from .triangle_hash import TriangleHash as _TriangleHash
ModuleNotFoundError: No module named 'utils.libs.libmesh.triangle_hash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_IPNet.py", line 12, in <module>
    from utils.voxelized_pointcloud_sampling import voxelize
  File "C:\Users\User\Desktop\Kiarash\IPNet\utils\voxelized_pointcloud_sampling.py", line 7, in <module>
    import utils.implicit_waterproofing as iw
  File "C:\Users\User\Desktop\Kiarash\IPNet\utils\implicit_waterproofing.py", line 12, in <module>
    from .libs_py27.libmesh import check_mesh_contains
ModuleNotFoundError: No module named 'utils.libs_py27'
```

I am using python 3.6 on windows 10.

I suspect I should install cython for the first error (although it was not in the requirements), But for the second error such a file doesn't even exist.

your implicit_waterproofing.py code (in the utils folder) has: 
`from .libs.libmesh import check_mesh_contains ` 
but there is no module check_mesh_contains !?

thank you

**Comment by bharat-b7** [comment]
Hi,

I haven't tested the code on windows but the error seems to originate from the following piece of code:
```
try:
    from .libs.libmesh import check_mesh_contains
except:
    '''try python 2.7 import '''
    from .libs_py27.libmesh import 
```
The second error you get comes because the `try` clause fails and it defaults to the `except`. The `except` just tries to import the python 2.7 version of the code in case you want to use python 2.7.
You just need to compile the `setup.py` with cython at `utils/libs/libmesh/`.

**Comment by KiyarashFarivar** [comment]
Thank you for the reply, I installed ubuntu and the libraries needed and now the code works. 

For any one using Windows, save yourself the headache and install Linux !

**Comment by codesavory** [comment]
This error continues to exist on Windows, I run the command - `python test_IPNet.py assets/scan.obj experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar out_dir -m IPNet` , I get the error - 
```
(IP-Net) D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet>python test_IPNet.py assets/scan.obj experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar out_dir -m IPNet
Traceback (most recent call last):
  File "test_IPNet.py", line 12, in <module>
    from utils.voxelized_pointcloud_sampling import voxelize
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\voxelized_pointcloud_sampling.py", line 7, in <module>
    import utils.implicit_waterproofing as iw
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\implicit_waterproofing.py", line 9, in <module>
    from .libs.libmesh import check_mesh_contains
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\libs\libmesh\__init__.py", line 1, in <module>
    from .inside_mesh import check_mesh_contains, MeshIntersector, TriangleIntersector2d
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\libs\libmesh\inside_mesh.py", line 3, in <module>
    from .triangle_hash import TriangleHash as _TriangleHash
ModuleNotFoundError: No module named 'utils.libs.libmesh.triangle_hash'
```

I compiled and installed libmesh from utils/libs/libmesh successfully - 
```
(IP-Net) D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\libs\libmesh>python setup.py install
running install
running bdist_egg
running egg_info
writing Hello_world_app.egg-info\PKG-INFO
writing dependency_links to Hello_world_app.egg-info\dependency_links.txt
writing top-level names to Hello_world_app.egg-info\top_level.txt
reading manifest file 'Hello_world_app.egg-info\SOURCES.txt'
writing manifest file 'Hello_world_app.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\utils
creating build\bdist.win-amd64\egg\utils\libs
creating build\bdist.win-amd64\egg\utils\libs\libmesh
copying build\lib.win-amd64-3.7\utils\libs\libmesh\triangle_hash.cp37-win_amd64.pyd -> build\bdist.win-amd64\egg\utils\libs\libmesh
creating stub loader for utils\libs\libmesh\triangle_hash.cp37-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\utils\libs\libmesh\triangle_hash.py to triangle_hash.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
utils.libs.libmesh.__pycache__.triangle_hash.cpython-37: module references __file__
creating 'dist\Hello_world_app-0.0.0-py3.7-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing Hello_world_app-0.0.0-py3.7-win-amd64.egg
removing 'c:\miniconda3\envs\ip-net\lib\site-packages\Hello_world_app-0.0.0-py3.7-win-amd64.egg' (and everything under it)
creating c:\miniconda3\envs\ip-net\lib\site-packages\Hello_world_app-0.0.0-py3.7-win-amd64.egg
Extracting Hello_world_app-0.0.0-py3.7-win-amd64.egg to c:\miniconda3\envs\ip-net\lib\site-packages
Hello-world-app 0.0.0 is already the active version in easy-install.pth

Installed c:\miniconda3\envs\ip-net\lib\site-packages\hello_world_app-0.0.0-py3.7-win-amd64.egg
Processing dependencies for Hello-world-app==0.0.0
Finished processing dependencies for Hello-world-app==0.0.0
```

**Comment by ClaudioCimarelli** [comment]
Hello everyone,

I am experiencing the exact same problem here. I am running this on an Nvidia Jetson platform and I have installed all the dependencies mentioned in the Readme. Has this anything to do with Trimesh? 

@kfarivar Could you explain to us what did you do more in detail to help us solve this?

Thank you.
