### ISSUE TITLE
import errors with libmesh on windows

### ISSUE THREAD

**Issue by codesavory** [bharat-b7/IPNet#28]
This error continues to exist on Windows, I run the command - `python test_IPNet.py assets/scan.obj experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar out_dir -m IPNet` , I get the error - 
```
(IP-Net) D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet>python test_IPNet.py assets/scan.obj experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar out_dir -m IPNet
Traceback (most recent call last):
  File "test_IPNet.py", line 12, in <module>
    from utils.voxelized_pointcloud_sampling import voxelize
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\voxelized_pointcloud_sampling.py", line 7, in <module>
    import utils.implicit_waterproofing as iw
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\implicit_waterproofing.py", line 9, in <module>
    from .libs.libmesh import check_mesh_contains
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\libs\libmesh\__init__.py", line 1, in <module>
    from .inside_mesh import check_mesh_contains, MeshIntersector, TriangleIntersector2d
  File "D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\libs\libmesh\inside_mesh.py", line 3, in <module>
    from .triangle_hash import TriangleHash as _TriangleHash
ModuleNotFoundError: No module named 'utils.libs.libmesh.triangle_hash'
```

I compiled and installed libmesh from utils/libs/libmesh successfully - 
```
(IP-Net) D:\CG_Source\NeRFs\3D_Avatar_Pipeline\IPNet\utils\libs\libmesh>python setup.py install
running install
running bdist_egg
running egg_info
writing Hello_world_app.egg-info\PKG-INFO
writing dependency_links to Hello_world_app.egg-info\dependency_links.txt
writing top-level names to Hello_world_app.egg-info\top_level.txt
reading manifest file 'Hello_world_app.egg-info\SOURCES.txt'
writing manifest file 'Hello_world_app.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\utils
creating build\bdist.win-amd64\egg\utils\libs
creating build\bdist.win-amd64\egg\utils\libs\libmesh
copying build\lib.win-amd64-3.7\utils\libs\libmesh\triangle_hash.cp37-win_amd64.pyd -> build\bdist.win-amd64\egg\utils\libs\libmesh
creating stub loader for utils\libs\libmesh\triangle_hash.cp37-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\utils\libs\libmesh\triangle_hash.py to triangle_hash.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Hello_world_app.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
utils.libs.libmesh.__pycache__.triangle_hash.cpython-37: module references __file__
creating 'dist\Hello_world_app-0.0.0-py3.7-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing Hello_world_app-0.0.0-py3.7-win-amd64.egg
removing 'c:\miniconda3\envs\ip-net\lib\site-packages\Hello_world_app-0.0.0-py3.7-win-amd64.egg' (and everything under it)
creating c:\miniconda3\envs\ip-net\lib\site-packages\Hello_world_app-0.0.0-py3.7-win-amd64.egg
Extracting Hello_world_app-0.0.0-py3.7-win-amd64.egg to c:\miniconda3\envs\ip-net\lib\site-packages
Hello-world-app 0.0.0 is already the active version in easy-install.pth

Installed c:\miniconda3\envs\ip-net\lib\site-packages\hello_world_app-0.0.0-py3.7-win-amd64.egg
Processing dependencies for Hello-world-app==0.0.0
Finished processing dependencies for Hello-world-app==0.0.0
```

_Originally posted by @codesavory in https://github.com/bharat-b7/IPNet/issues/10#issuecomment-883059042_

**Comment by ClaudioCimarelli** [comment]
Hi, I just managed to solved this.
Remove any *.so file and do `python setup.py build_ext`

If you have a FileExist error, just manually copy the newly created .so file in libmesh folder and name it triangle_hash.so. 
It should work :)
